### ISSUE TITLE
打出来的镜像加载后无法开机直接黑屏

### ISSUE THREAD

**Issue by powerAn2020** [zfdx123/kernel_xiaomi_alioth#1]
大佬可以请教下打包流程和环境吗？我fork代码用GitHub action导出镜像但是刷入后无法开机。

**Comment by zfdx123** [comment]
在我拉取Linux kernel 282更新到由291之后无法开启，修复了几个冲突和错误，还没找到是哪导致的无法开机，可以先回滚到 6f5c7d6e6b9d1d3a4ac177c70c6a5966aca1920f 这次提交使用，我最近刚拉delta到magisk的最新提交所以一直没修复，我最近可能会测试内核，修复开机问题，如果你有能力欢迎pr

**Comment by zfdx123** [comment]
修复完成设备启动成功，这是我的编译库 https://github.com/zfdx123/build-k40-ksu 供参考

**Comment by powerAn2020** [comment]
感谢大佬
